-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE OR REPLACE FUNCTION increment_storage_used(p_user_id UUID, p_bytes BIGINT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN UPDATE profiles SET storage_used = COALESCE(storage_used, 0) + p_bytes WHERE id = p_user_id; END; $$;
