-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS storage_used BIGINT DEFAULT 0; ALTER TABLE profiles ADD COLUMN IF NOT EXISTS storage_limit BIGINT DEFAULT 1073741824;
