-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建用户角色枚举
CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');

-- 创建用户资料表
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  avatar_url TEXT,
  display_name TEXT,
  bio TEXT,
  is_banned BOOLEAN DEFAULT FALSE,
  storage_used BIGINT DEFAULT 0,
  storage_limit BIGINT DEFAULT 1073741824, -- 默认1GB
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建用户角色表
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role public.app_role NOT NULL DEFAULT 'user',
  UNIQUE (user_id, role)
);

-- 创建图片分类表
CREATE TABLE public.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建图片表
CREATE TABLE public.images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  mime_type TEXT NOT NULL,
  width INTEGER,
  height INTEGER,
  thumbnail_path TEXT,
  category_id UUID REFERENCES public.categories(id) ON DELETE SET NULL,
  tags TEXT[],
  is_public BOOLEAN DEFAULT TRUE,
  is_approved BOOLEAN DEFAULT FALSE,
  is_featured BOOLEAN DEFAULT FALSE,
  download_count INTEGER DEFAULT 0,
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建收藏表
CREATE TABLE public.favorites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  image_id UUID REFERENCES public.images(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (user_id, image_id)
);

-- 创建系统设置表
CREATE TABLE public.system_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL,
  description TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 插入默认分类
INSERT INTO public.categories (name, description, sort_order) VALUES
  ('训练日常', '仪仗队日常训练照片', 1),
  ('升旗仪式', '升旗仪式活动照片', 2),
  ('重大活动', '学校重大活动照片', 3),
  ('团队建设', '团队建设活动照片', 4),
  ('荣誉时刻', '获奖和荣誉照片', 5);

-- 插入默认系统设置
INSERT INTO public.system_settings (key, value, description) VALUES
  ('site_name', '"浙江大学国旗仪仗队图片库"', '网站名称'),
  ('max_upload_size', '10485760', '最大上传文件大小（字节，默认10MB）'),
  ('allowed_formats', '["image/jpeg", "image/png", "image/gif", "image/webp"]', '允许上传的图片格式'),
  ('default_storage_limit', '1073741824', '默认用户存储空间限制（字节，1GB）'),
  ('require_approval', 'true', '上传图片是否需要审核');

-- 启用RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- 创建角色检查函数
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN
LANGUAGE SQL STABLE
SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- Profiles RLS策略
CREATE POLICY "公开查看用户资料" ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "用户可更新自己的资料" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "管理员可管理所有用户资料" ON public.profiles
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- User Roles RLS策略
CREATE POLICY "公开查看用户角色" ON public.user_roles
  FOR SELECT USING (true);

CREATE POLICY "仅管理员可管理角色" ON public.user_roles
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- Categories RLS策略
CREATE POLICY "公开查看分类" ON public.categories
  FOR SELECT USING (true);

CREATE POLICY "管理员可管理分类" ON public.categories
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- Images RLS策略
CREATE POLICY "公开查看已审核图片" ON public.images
  FOR SELECT USING (is_approved = true AND is_public = true);

CREATE POLICY "用户可查看自己的所有图片" ON public.images
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "管理员可查看所有图片" ON public.images
  FOR SELECT USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'moderator'));

CREATE POLICY "用户可上传图片" ON public.images
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户可更新自己的图片" ON public.images
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户可删除自己的图片" ON public.images
  FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "管理员可管理所有图片" ON public.images
  FOR ALL USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'moderator'));

-- Favorites RLS策略
CREATE POLICY "用户可查看自己的收藏" ON public.favorites
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "用户可添加收藏" ON public.favorites
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "用户可删除自己的收藏" ON public.favorites
  FOR DELETE USING (user_id = auth.uid());

-- System Settings RLS策略
CREATE POLICY "公开查看系统设置" ON public.system_settings
  FOR SELECT USING (true);

CREATE POLICY "仅管理员可修改系统设置" ON public.system_settings
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- 创建存储桶
INSERT INTO storage.buckets (id, name, public) VALUES
  ('images', 'images', true),
  ('avatars', 'avatars', true);

-- Storage RLS策略
CREATE POLICY "公开访问图片" ON storage.objects
  FOR SELECT USING (bucket_id = 'images');

CREATE POLICY "公开访问头像" ON storage.objects
  FOR SELECT USING (bucket_id = 'avatars');

CREATE POLICY "认证用户可上传图片" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'images' AND
    auth.role() = 'authenticated'
  );

CREATE POLICY "认证用户可上传头像" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'avatars' AND
    auth.role() = 'authenticated'
  );

CREATE POLICY "用户可删除自己的图片" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'images' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "用户可删除自己的头像" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'avatars' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- 创建新用户触发器
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username, email, display_name)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data ->> 'username',
    NEW.email,
    NEW.raw_user_meta_data ->> 'username'
  );
  
  -- 默认分配user角色
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user');
  
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();