-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


DO $$
DECLARE
 admin_user_id UUID;
 admin_email TEXT := 'gqyzd@meoo.local';
 admin_username TEXT := 'gqyzd';
 admin_password TEXT := 'ZJUgqyzd1997';
BEGIN
 SELECT id INTO admin_user_id FROM auth.users WHERE email = admin_email;
 
 IF admin_user_id IS NULL THEN
 INSERT INTO auth.users (
 id, instance_id, email, encrypted_password, email_confirmed_at,
 confirmation_token, recovery_token, email_change_token_new,
 email_change, raw_app_meta_data, raw_user_meta_data,
 is_super_admin, created_at, updated_at, phone, phone_change,
 phone_change_token, email_change_token_current,
 email_change_confirm_status, reauthentication_token,
 is_sso_user, deleted_at, is_anonymous
 ) VALUES (
 gen_random_uuid(), '00000000-0000-0000-0000-000000000000',
 admin_email, crypt(admin_password, gen_salt('bf')), NOW(),
 '', '', '', '',
 '{"provider":"email","providers":["email"]}',
 format('{"username":"%s"}', admin_username)::jsonb,
 FALSE, NOW(), NOW(), NULL, '', '', '', 0, '', FALSE, NULL, FALSE
 ) RETURNING id INTO admin_user_id;
 ELSE
 UPDATE auth.users 
 SET encrypted_password = crypt(admin_password, gen_salt('bf'))
 WHERE email = admin_email;
 END IF;
 
 INSERT INTO profiles (id, username, display_name, created_at, updated_at)
 VALUES (admin_user_id, admin_username, '管理员', NOW(), NOW())
 ON CONFLICT (id) DO NOTHING;
 
 INSERT INTO user_roles (user_id, role)
 VALUES (admin_user_id, 'admin')
 ON CONFLICT (user_id, role) DO NOTHING;
END $$;

