-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE OR REPLACE FUNCTION confirm_admin_user(
 p_user_id UUID,
 p_display_name TEXT DEFAULT '管理员'
) RETURNS VOID AS $$
BEGIN
 -- 确认邮箱
 UPDATE auth.users 
 SET email_confirmed_at = NOW()
 WHERE id = p_user_id;
 
 -- 更新 profile 显示名称
 UPDATE profiles 
 SET display_name = p_display_name
 WHERE id = p_user_id;
 
 -- 赋予 admin 角色
 INSERT INTO user_roles (user_id, role)
 VALUES (p_user_id, 'admin')
 ON CONFLICT (user_id, role) DO NOTHING;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

