-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE OR REPLACE FUNCTION public.increment_view_count(image_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  UPDATE public.images
  SET view_count = COALESCE(view_count, 0) + 1
  WHERE id = image_id;
END;
$$;