-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE public.years (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  year INTEGER UNIQUE NOT NULL,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE public.locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.images ADD COLUMN year_id UUID REFERENCES public.years(id) ON DELETE SET NULL;
ALTER TABLE public.images ADD COLUMN location_id UUID REFERENCES public.locations(id) ON DELETE SET NULL;

ALTER TABLE public.years ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看年份" ON public.years FOR SELECT USING (true);
CREATE POLICY "仅管理员可编辑年份" ON public.years FOR ALL USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "所有人可查看地点" ON public.locations FOR SELECT USING (true);
CREATE POLICY "仅管理员可编辑地点" ON public.locations FOR ALL USING (public.has_role(auth.uid(), 'admin'));

INSERT INTO public.years (year, description, sort_order) VALUES
  (1997, '浙江大学国旗仪仗队成立之年', 1),
  (1998, NULL, 2),
  (1999, NULL, 3),
  (2000, '千禧年', 4),
  (2001, NULL, 5),
  (2002, NULL, 6),
  (2003, NULL, 7),
  (2004, NULL, 8),
  (2005, NULL, 9),
  (2006, NULL, 10),
  (2007, NULL, 11),
  (2008, '北京奥运会', 12),
  (2009, NULL, 13),
  (2010, NULL, 14),
  (2011, NULL, 15),
  (2012, NULL, 16),
  (2013, NULL, 17),
  (2014, NULL, 18),
  (2015, NULL, 19),
  (2016, NULL, 20),
  (2017, '浙江大学建校120周年', 21),
  (2018, NULL, 22),
  (2019, NULL, 23),
  (2020, NULL, 24),
  (2021, NULL, 25),
  (2022, NULL, 26),
  (2023, NULL, 27),
  (2024, NULL, 28),
  (2025, NULL, 29);

INSERT INTO public.locations (name, description, sort_order) VALUES
  ('紫金港校区', '浙江大学主校区', 1),
  ('玉泉校区', '浙江大学老校区', 2),
  ('西溪校区', '浙江大学西溪校区', 3),
  ('之江校区', '浙江大学之江校区', 4),
  ('华家池校区', '浙江大学华家池校区', 5),
  ('校外活动', '校外各类活动', 6);