-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE OR REPLACE FUNCTION create_admin_user(
 p_username TEXT,
 p_password TEXT,
 p_display_name TEXT DEFAULT '管理员'
) RETURNS VOID AS $$
DECLARE
 v_user_id UUID;
 v_email TEXT;
BEGIN
 v_email := p_username || '@meoo.local';
 
 -- 检查用户是否已存在
 SELECT id INTO v_user_id FROM auth.users WHERE email = v_email;
 
 IF v_user_id IS NULL THEN
 INSERT INTO auth.users (
 id, instance_id, email, encrypted_password, email_confirmed_at,
 raw_app_meta_data, raw_user_meta_data,
 is_super_admin, created_at, updated_at, is_anonymous
 ) VALUES (
 gen_random_uuid(),
 '00000000-0000-0000-0000-000000000000',
 v_email,
 extensions.crypt(p_password, extensions.gen_salt('bf')),
 NOW(),
 '{"provider":"email","providers":["email"]}',
 format('{"username":"%s"}', p_username)::jsonb,
 FALSE, NOW(), NOW(), FALSE
 ) RETURNING id INTO v_user_id;
 
 -- 创建或更新 profile（使用 ON CONFLICT）
 INSERT INTO profiles (id, username, display_name, created_at, updated_at)
 VALUES (v_user_id, p_username, p_display_name, NOW(), NOW())
 ON CONFLICT (id) DO UPDATE SET 
 username = EXCLUDED.username,
 display_name = EXCLUDED.display_name,
 updated_at = NOW();
 
 -- 赋予 admin 角色
 INSERT INTO user_roles (user_id, role)
 VALUES (v_user_id, 'admin')
 ON CONFLICT (user_id, role) DO NOTHING;
 END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

