/**
 * 🚨 此文件由 CloudEnableTool 自动生成，请勿手动修改！
 * This file is auto-generated by CloudEnableTool. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export function getSupabaseUrl(): string {
  // 优先使用 MEOO_CONFIG（Meoo 平台注入）
  const configUrl = (window as any).MEOO_CONFIG?.meoo_app_access_url;
  if (configUrl) {
    return `${configUrl}/sb-api`;
  }

  // 固定使用当前云服务地址，确保所有环境都能访问同一数据库
  return 'https://afp2yuczys3x.meoo.host/sb-api';
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzc3OTgwNjE3LCJleHAiOjEzMjg4NjIwNjE3fQ.VJiFUTyNn_etAFbXJOfeApj05kLxi3qVLtmv47QrSGA';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Accept': 'application/json',
    },
  },
});
